sudo: required
services:
  -docker
before_install:
  - docker build -t dev_frontend -f Dockerfile.dev .
script:
  - docker run dev_frontend npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-demo"
  env: "DockerDemo-env"
  bucket_name: "elasticbeanstalk-us-east-2-155213612701"
  bucket_path: "Docker-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

