sudo: required
services:
  -docker
before_install:
  - docker build -t dev_frontend -f Dockerfile.dev .
script:
  - docker run dev_frontend npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Ndocker"
  env: "Ndocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-155213612701"
  bucket_path: "Ndocker-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


#DEMO

